name: "CI Test Info gatherer"

on:
  pull_request:
    paths:
      - '**/*.yaml'
      - '**/*.json'

env:
  PROJECT_ID: "YOUR_PROJECT_ID"
  LOCATION: "YOUR_LOCATION"
  GCP_WORKLOAD_IDENTITY_PROVIDER: "projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider"
  GCP_SERVICE_ACCOUNT: "my-service-account@my-project.iam.gserviceaccount.com" 

jobs:
  test-info_gatherer:
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Authenticate to Google Cloud via Workload Identity Federation
      # See https://github.com/google-github-actions/auth for configuration instructions
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}

      - name: Install cxas-scrapi CLI
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/GoogleCloudPlatform/cxas-scrapi.git

      - name: Run CI Test Lifecycle
        run: |
          cxas-eval ci-test --agent_dir . \
                            --project_id ${{ env.PROJECT_ID }} \
                            --location ${{ env.LOCATION }}
