name: "Cleanup Information gatherer"

on:
  pull_request:
    types: [closed]
    paths:
      - 'Info_gatherer/**/*.yaml'
      - 'Info_gatherer/**/*.json'

env:
  PROJECT_ID: "YOUR_PROJECT_ID"
  LOCATION: "YOUR_LOCATION"
  GCP_WORKLOAD_IDENTITY_PROVIDER: "projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider"
  GCP_SERVICE_ACCOUNT: "my-service-account@my-project.iam.gserviceaccount.com" 

jobs:
  cleanup-information_gatherer:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event.pull_request.closed == true

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Authenticate to Google Cloud via Workload Identity Federation
      # See https://github.com/google-github-actions/auth for configuration instructions
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Install cxas-scrapi CLI
        run: |
          python -m pip install --upgrade pip
          wget https://storage.googleapis.com/gassets-api-ai/ces-client-libraries/v1beta/ces-v1beta-py.tar
          pip install ces-v1beta-py.tar --quiet
          pip install cxas-scrapi

      - name: Run Cleanup
        run: |
          cxas-eval delete --display_name "[CI] PR-${{ github.event.pull_request.number }} Information gatherer" \
                   --project_id ${{ env.PROJECT_ID }} \
                   --location ${{ env.LOCATION }}
